/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NanoClock */

#ifndef _Included_com_caplin_time_NanoClock
#define _Included_com_caplin_time_NanoClock
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_caplin_time_NanoClock
 * Method:    clock_gettime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_caplin_time_NanoClock_clock_1gettime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
